ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.iadel.joke.plugins.SerializationKt.configureSerialization
      com.iadel.joke.plugins.HTTPKt.configureHTTP
      com.iadel.joke.plugins.RoutingKt.configureRouting
    ]
  }
}